version: '3'

services:
  backend-server:
    build:
      context: server
      dockerfile: docker/dev.dockerfile
    ports:
      - 8889:8889
    volumes:
      - "./server:/root"
      - "${GENEY_DATA_PATH}:/root/data"
      - "${DOWNLOAD_LOCATION}:/root/downloads"
    environment:
      - GENEY_DATA_PATH=/root/data
      - GENEY_URL=localhost
      - DOWNLOAD_LOCATION=/root/downloads
  
  redis:
    image: "redis:alpine"

  site:
    build:
      context: site
      dockerfile: docker/dev.dockerfile
    ports:
      - 8080:8080
    volumes:
      - "./site:/root"